DEBUG 2018-06-11 23:19:34,078: 	 Executing command: 'status'
DEBUG 2018-06-11 23:19:34,078: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
ERROR 2018-06-11 23:19:34,118: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area
ERROR 2018-06-11 23:19:34,118: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area
DEBUG 2018-06-19 00:16:40,206: 	 Executing command: 'status'
DEBUG 2018-06-19 00:16:40,206: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
ERROR 2018-06-19 00:16:40,233: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area
ERROR 2018-06-19 00:16:40,233: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area
DEBUG 2018-06-19 16:06:58,141: 	 Executing command: 'status'
DEBUG 2018-06-19 16:06:58,142: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
ERROR 2018-06-19 16:06:58,215: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area_test
ERROR 2018-06-19 16:06:58,215: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1019, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area_test
DEBUG 2018-06-19 16:09:41,127: 	 Executing command: 'resubmit'
DEBUG 2018-06-19 16:09:41,127: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-06-21 00:15:43,432: 	 Executing command: 'resubmit'
DEBUG 2018-06-21 00:15:43,434: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-06-21 09:23:59,206: 	 Executing command: 'resubmit'
DEBUG 2018-06-21 09:23:59,206: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-06-21 09:24:36,042: 	 Executing command: 'submit'
DEBUG 2018-06-21 09:24:36,042: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-06-22 10:23:54,589: 	 Executing command: 'resubmit'
DEBUG 2018-06-22 10:23:54,589: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-06-22 11:10:18,319: 	 Executing command: 'kill'
DEBUG 2018-06-22 11:10:18,319: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-06-22 11:11:59,102: 	 Executing command: 'resubmit'
DEBUG 2018-06-22 11:11:59,102: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-06-22 11:44:22,576: 	 Executing command: 'submit'
DEBUG 2018-06-22 11:44:22,576: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-06-22 11:44:22,592: 	 Checking credentials
DEBUG 2018-06-22 11:44:22,593: 	 Found proxy file /tmp/x509up_u95116
DEBUG 2018-06-22 11:44:22,593: 	 Getting proxy life time left
DEBUG 2018-06-22 11:44:23,809: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u95116 -timeleft
 output : 37765

 error: 
 retcode : 0
DEBUG 2018-06-22 11:44:25,338: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u95116 -actimeleft
 output : 37763

 error: 
 retcode : 0
DEBUG 2018-06-22 11:44:25,339: 	 Proxy valid for 10:29:25 hours
INFO 2018-06-22 11:44:25,339: 	 Will use CRAB configuration file crab3_config.py
DEBUG 2018-06-22 11:44:25,339: 	 Loading CRAB configuration file.
DEBUG 2018-06-22 11:44:25,369: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2018-06-22 11:44:25,369: 	 Invalid CRAB configuration:
 when ignoreLocality is set a valid site white list must be specified using the Site.whitelist parameter
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-06-22 11:44:25,370: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 89, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration:
 when ignoreLocality is set a valid site white list must be specified using the Site.whitelist parameter
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-07-20 13:04:13,112: 	 Executing command: 'submit'
DEBUG 2018-07-20 13:04:13,112: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-07-20 13:04:13,139: 	 Checking credentials
DEBUG 2018-07-20 13:04:13,140: 	 Found proxy file /tmp/x509up_u95116
DEBUG 2018-07-20 13:04:13,140: 	 Getting proxy life time left
DEBUG 2018-07-20 13:04:13,946: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u95116 -timeleft
 output : 42385

 error: 
 retcode : 0
DEBUG 2018-07-20 13:04:14,652: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u95116 -actimeleft
 output : 42384

 error: 
 retcode : 0
DEBUG 2018-07-20 13:04:14,653: 	 Proxy valid for 11:46:25 hours
INFO 2018-07-20 13:04:14,654: 	 Will use CRAB configuration file crab3_config.py
DEBUG 2018-07-20 13:04:14,654: 	 Loading CRAB configuration file.
ERROR 2018-07-20 13:04:14,667: 	 Error while loading CRAB configuration:
EOL while scanning string literal (crab3_config.py, line 8)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2018-07-20 13:04:14,668: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
EOL while scanning string literal (crab3_config.py, line 8)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2018-07-31 17:52:17,982: 	 Executing command: 'submit'
DEBUG 2018-07-31 17:52:17,983: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-07-31 17:52:18,008: 	 Checking credentials
DEBUG 2018-07-31 17:52:18,009: 	 Found proxy file /tmp/x509up_u95116
DEBUG 2018-07-31 17:52:18,009: 	 Getting proxy life time left
DEBUG 2018-07-31 17:52:18,818: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u95116 -timeleft
 output : 40565

 error: 
 retcode : 0
DEBUG 2018-07-31 17:52:19,727: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u95116 -actimeleft
 output : 40564

 error: 
 retcode : 0
DEBUG 2018-07-31 17:52:19,727: 	 Proxy valid for 11:16:05 hours
INFO 2018-07-31 17:52:19,727: 	 Will use CRAB configuration file crab3_config.py
DEBUG 2018-07-31 17:52:19,727: 	 Loading CRAB configuration file.
DEBUG 2018-07-31 17:52:19,764: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2018-07-31 17:52:19,776: 	 Working area '/afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area_newpedestals/crab_TagAndProbe' already exists 
Please change the requestName in the config file
ERROR 2018-07-31 17:52:19,776: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 307, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area_newpedestals/crab_TagAndProbe' already exists 
Please change the requestName in the config file
DEBUG 2018-08-01 14:46:44,232: 	 Executing command: 'submit'
DEBUG 2018-08-01 14:46:44,235: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-08-01 14:46:44,262: 	 Checking credentials
DEBUG 2018-08-01 14:46:44,268: 	 Found proxy file /tmp/x509up_u95116
DEBUG 2018-08-01 14:46:44,268: 	 Getting proxy life time left
DEBUG 2018-08-01 14:46:45,476: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u95116 -timeleft
 output : 43091

 error: 
 retcode : 0
DEBUG 2018-08-01 14:46:46,827: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u95116 -actimeleft
 output : 43089

 error: 
 retcode : 0
DEBUG 2018-08-01 14:46:46,827: 	 Proxy valid for 11:58:11 hours
INFO 2018-08-01 14:46:46,827: 	 Will use CRAB configuration file crab3_config_sameCondition.py
DEBUG 2018-08-01 14:46:46,828: 	 Loading CRAB configuration file.
DEBUG 2018-08-01 14:46:46,848: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2018-08-01 14:46:46,887: 	 Working area '/afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area_newpedestals/crab_TagAndProbe' already exists 
Please change the requestName in the config file
ERROR 2018-08-01 14:46:46,888: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 307, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area_newpedestals/crab_TagAndProbe' already exists 
Please change the requestName in the config file
DEBUG 2018-08-01 15:38:33,736: 	 Executing command: 'submit'
DEBUG 2018-08-01 15:38:33,740: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-08-01 15:38:33,778: 	 Checking credentials
DEBUG 2018-08-01 15:38:33,780: 	 Found proxy file /tmp/x509up_u95116
DEBUG 2018-08-01 15:38:33,780: 	 Getting proxy life time left
ERROR 2018-08-01 15:38:34,927: 	 Keyboard Interrupted
DEBUG 2018-08-01 18:34:19,854: 	 Executing command: 'submit'
DEBUG 2018-08-01 18:34:19,856: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
DEBUG 2018-08-01 18:34:19,865: 	 Checking credentials
DEBUG 2018-08-01 18:34:19,866: 	 Found proxy file /tmp/x509up_u95116
DEBUG 2018-08-01 18:34:19,866: 	 Getting proxy life time left
DEBUG 2018-08-01 18:34:20,673: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u95116 -timeleft
 output : 13913

 error: 
 retcode : 0
DEBUG 2018-08-01 18:34:21,383: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u95116 -actimeleft
 output : 13912

 error: 
 retcode : 0
DEBUG 2018-08-01 18:34:21,384: 	 Proxy valid for 03:51:53 hours
INFO 2018-08-01 18:34:21,384: 	 Will use CRAB configuration file crab3_config_lowstat.py
DEBUG 2018-08-01 18:34:21,384: 	 Loading CRAB configuration file.
DEBUG 2018-08-01 18:34:21,391: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2018-08-01 18:34:21,391: 	 Working area '/afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area_newpedestals/crab_TagAndProbe' already exists 
Please change the requestName in the config file
ERROR 2018-08-01 18:34:21,391: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 307, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area_newpedestals/crab_TagAndProbe' already exists 
Please change the requestName in the config file
DEBUG 2018-08-03 11:35:42,850: 	 Executing command: 'resubmit'
DEBUG 2018-08-03 11:35:42,851: 	 Found CRAB cache file /afs/cern.ch/user/s/syuan/.crab3
ERROR 2018-08-03 11:35:42,882: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area_newpedestals_updatecalo
ERROR 2018-08-03 11:35:42,882: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 28, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/resubmit.py", line 276, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1805.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/s/syuan/cmssw/CMSSW_10_1_5/src/EGTagAndProbe/EGTagAndProbe/test/DefaultCrab3Area_newpedestals_updatecalo
